config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  post 'authenticate', to: 'authentication#authenticate'
  post '/auth/signup', to:'authentication#signup'

  root 'users#index'
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    user ||= User.new
    can :read, Post

    return unless user.present?

    can :manage, Post, author_id: user.id
    can :manage, Comment, author_id: user.id
    return unless user.role == 'admin'

    can :manage, :all
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_create :update_post_comment_counter
  def update_post_comment_counter
    post.comments_counter = 0 unless post.comments_counter?
    post.comments_counter += 1
    post.save
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_create :update_post_like_counter

  def update_post_like_counter
    post.likes_counter = 0 unless post.likes_counter?
    post.likes_counter += 1
    post.save
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :delete_all
  has_many :likes, dependent: :delete_all

  validates :text, presence: true, length: { maximum: 250, minimum: 1 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_create :update_posts_count
  def update_posts_count
    author.posts_counter = 0 unless author.posts_counter?
    author.posts_counter += 1
    author.save
  end

  def most_recent_comments
    Comment.includes(:author).where(post: self).order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'

  validates :name, presence: true
  # validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  def recent_post
    Post.where(author: self).order(created_at: :desc).limit(3)
  end

  def authenticate(pwd)
    password == pwd
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  # before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  before_action :authenticate_request, if: :json_request
  attr_reader :current_user

  private

  def authenticate_request
    @current_user = AuthorizeApiRequest.call(request.headers).result
    render json: { error: 'Not Authorized' }, status: 401 unless @current_user
  end

  def json_request
    request.format.json?
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :photo, :email, :password, :password_confirmation, :bio)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :photo, :email, :password, :current_password, :bio)
    end
  end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  skip_before_action :authenticate_request

  def authenticate
    command = AuthenticateUser.call(params[:email], params[:password])

    if command.success?
      render json: { auth_token: command.result }
    else
      render json: { error: command.errors }, status: :unauthorized
    end
  end

  def signup
    @user = User.new(
      name: params[:name], photo: params[:photo], bio: params[:bio], posts_counter: 0,
      email: params[:email], password: params[:password],
      password_confirmation: params[:password_confirmation]
    )
    if @user.save
      render json: @user, status: :created
    else
      render json: { errors: @user.errors.full_messages }, status: :unprocessable_entity
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @recent_comments = @post.most_recent_comments
  end

  def create
    respond_to do |format|
      format.json do
        authenticate_request
        comment = Comment.new(post_id: params[:post_id], author_id: current_user.id, text: parameters[:text])
        comment.save
        render json: "New Comment Added By #{current_user.name}"
      end
      format.html do
        comment = Comment.new(author: current_user, post_id: params[:post_id], text: params[:text])
        comment.save
        if comment.save
          redirect_to user_post_path(user_id: params[:user_id], id: params[:post_id])
        else
          redirect_to new_user_post_comment_path
        end
      end
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    like = Like.new(author: current_user, post_id: params[:post_id])
    like.save
    redirect_back(fallback_location: root_path) if like.save
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = Post.where(author: @user)

    respond_to do |format|
      format.html
      format.json { render json: @posts }
    end
  end

  def show
    @post = Post.find_by(id: params[:id], author_id: params[:user_id])
    @comments = @post.most_recent_comments

    respond_to do |format|
      format.html
      format.json { render json: @post.comments }
    end
  end

  def new
    @new_post = Post.new
    @user = current_user
  end

  def create
    respond_to do |format|
      format.html do
        post = Post.new(author: current_user, title: params[:title], text: params[:text], comments_counter: 0,
                        likes_counter: 0)
        post.save
        if post.save
          redirect_to user_posts_path(current_user)
        else
          redirect_to new_user_post_path
        end
      end

      format.json do
        authenticate_request
        post = Post.new(author: current_user, title: params[:title], text: params[:text], comments_counter: 0,
                        likes_counter: 0)
        render json: "New Post created by #{current_user.name}" if post.save
      end
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    flash[:notice] = 'Post has been deleted!'
    redirect_to user_posts_path(current_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    if params[:id] == 'sign_out'
      sign_out current_user
      redirect_to root_path
    else
      @user = User.find(params[:id])
      @recent_posts = @user.recent_post
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentication_helper.rb
module AuthenticationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<div class= ' flex flex-col gap-4 mt-4'>
  <div class='flex flex-col gap-4 shadow-md shadow-slate-400 p-4 rounded-md'>
    <div class='flex flex-col'>
      <h2 class=' text-3xl font-bold mb-8 '>Author: <%= @user.name %></h2>
      <div class='flex flex-col gap-4'>
        <h2 class=' text-3xl'><%= @post.title %></h2>
        <p class=' pl-8'><%= @post.text %></p>
      </div>
      <div class='flex gap-4 self-end bg-orange-200 p-4 rounded-md'>
        <p><%= @post.comments_counter %> Comments</p>
        <p><%= @post.likes_counter %> Likes</p>
      </div>
    </div>
  </div>
<!--  forms to add comment-->
  <div class=' bg-slate-500 p-4 rounded-lg'>
    <%= form_with url: user_post_comments_path do |form| %>
      <div class="flex flex-col gap-8">
        <div class="flex flex-col gap-4">
          <%= form.label :text, "Enter Comment:", class:'text-white' %>
          <%= form.text_field :text, class: 'rounded-full' %>
        </div>

        <%= form.submit "Add comment", class: 'text-white' %>


      </div>
    <% end %>
  </div>

  <div class='flex flex-col gap-8 my-8 shadow-md shadow-slate-400 p-4 rounded-md'>
    <h2 class=' text-2xl'>Comments</h2>
    <% @recent_comments.each do |comment| %>
      <div class=' flex gap-4 items-center'>
        <div class=' flex gap-4 justify-start items-center px-4 border-r-4'>
          <img src="<%= comment.author.photo %>" alt="<%= comment.author.name %>" class='w-16 h-16 rounded-full'>
          <p><%= comment.author.name %></p>
        </div>
        <div class='pl-8'>
          <p><%= comment.text %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto px-5 flex flex-col gap-4">
      <div class="flex gap-8 self-end mt-4">
        <% if user_signed_in? %>
          <%= link_to 'Sign Out' ,destroy_user_session_path, method: :delete %>
        <%else %>
          <%= link_to 'Sign In' ,new_user_session_path%>
          <%= link_to 'Sign Up' ,new_user_registration_path%>
        <% end %>
      </div>

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/index.html.erb
<div class='flex flex-col gap-4 mt-8'>
  <div class='flex gap-8 items-center'>
    <img src="<%= @user.photo %>" alt="<%= @user.name %>" class='w-32 h-32 rounded-full'>
    <div class="flex flex-col">
      <h1 class=" text-3xl"><%= @user.name %></h1>
      <p><%= @user.posts_counter%> posts</p>
    </div>
  </div>

  <div class=' self-end mb-8 shadow-md shadow-slate-400 p-4 rounded-md'>
    <%= button_to "New Post", new_user_post_path, method:'get' %>
  </div>

  <div class='flex flex-col gap-4 mt-4'>
    <% @posts.each_with_index do |post, idx| %>
      <%= link_to user_post_path(user_id: @user.id, id: post.id) do %>
        <div class="flex flex-col gap-4 bg-slate-500 text-white p-4 rounded-lg">
          <p class=' text-xl'>Post <%= idx + 1 %></p>
          <h2 class=' text-3xl'><%= post.title %></h2>
          <p class=' pl-8'><%= post.text %></p>

          <div class='flex self-end gap-4 bg-white p-4 text-slate-800 rounded-md'>
            <p ><%=post.comments_counter %> comments</p>
            <p><%=post.likes_counter %> likes</p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class=' self-end mb-8 shadow-md shadow-slate-400 p-4 rounded-md'>
    <%= button_to "Pagination" %>
  </div>
</div>

app/views/posts/new.html.erb
<div class='flex flex-col gap-4 mt-4'>
  <h1 class=' text-2xl'>New post</h1>
  <div class=' flex gap-8 items-center'>
    <img src="<%= @user.photo %>>" alt="<%= @user.name %>>" class='w-32 h-32 rounded-full'>
    <h1 class=' text-2xl'><%= @user.name %></h1>
  </div>

    <%= form_with model: @post, url: user_posts_path  do |form| %>
      <div class = 'flex flex-col gap-4'>
        <div class='flex gap-8 items-center'>
          <%= form.label :title, "Title: " %>
          <%= form.text_field :title, class: 'rounded-full' %>
        </div>
        <div class='flex gap-8 items-center'>
          <%= form.label :text, "Text: " %>
          <%= form.text_field :text, class: 'rounded-full' %>
        </div>
        <div>
          <%= form.submit 'Submit Post', class: 'shadow-md shadow-slate-400 p-4 rounded-md self-start' %>
        </div>
      </div>
      
    <% end %>
</div>

app/views/posts/show.html.erb
<div class= ' flex flex-col gap-4 mt-4'>
  <div class='flex flex-col gap-4 shadow-md shadow-slate-400 p-4 rounded-md'>
    <div class='flex flex-col'>
      <h2 class=' text-3xl font-bold mb-8 '>Author: <%= @post.author.name %></h2>
      <div class='flex flex-col gap-4'>
        <h2 class=' text-3xl'><%= @post.title %></h2>
        <p class=' pl-8'><%= @post.text %></p>
      </div>
      <div class='flex gap-4 self-end bg-orange-200 p-4 rounded-md'>
        <p><%= @post.comments_counter %> Comments</p>
        <p><%= @post.likes_counter %> Likes</p>
      </div>
      <div class="flex gap-8 self-end">
        <div class="self-end shadow-md shadow-slate-400 p-4 rounded-md mt-4">
          <%= button_to "Add Comment", new_user_post_comment_path(user_id: @post.author.id, post_id: @post.id), method:'get' %>
        </div>
        <div class="self-end shadow-md shadow-slate-400 p-4 rounded-md mt-4">
          <%= button_to "Like Post", user_post_likes_path(user_id: @post.author.id, post_id: @post.id), method:'post' %>
        </div>
        <% if can? :destroy, @post %>
          <div class="self-end shadow-md shadow-slate-400 p-4 rounded-md mt-4">
            <%= button_to "Delete Post", user_post_path(user_id: @post.author.id, post_id: @post.id), method: :delete %>
          </div>
        <%end %>
      </div>

    </div>
  </div>

  <div class='flex flex-col gap-8 my-8 shadow-md shadow-slate-400 p-4 rounded-md'>
  <h2 class=' text-2xl'>Comments</h2>
    <% @comments.each do |comment| %>
      <div class=' flex gap-4 items-center'>
        <div class=' flex gap-4 justify-start items-center px-4 border-r-4'>
          <img src="<%= comment.author.photo %>" alt="<%= comment.author.name %>" class='w-16 h-16 rounded-full'>
          <p><%= comment.author.name %></p>
        </div>
        <div class='pl-8'>
          <p><%= comment.text %></p>
        </div>
        <% if can? :destroy, comment %>
          <div class="self-end shadow-md shadow-slate-400 p-4 rounded-md mt-4">
            <%= button_to "Delete Comment", user_post_comment_path(user_id: @post.author.id, post_id: @post.id, id: comment.id), method: :delete %>
          </div>
        <%end %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1 class='text-5xl my-4'>Users</h1>
<h3>Select one to see there detailed post.</h3>

<div class='flex flex-col gap-8 mt-8'>
  <% @users.each do |user|%>
      <div class= 'flex gap-8 items-center' id="<%= user.id %>">
        <%= link_to user_path(id: user.id) do %>
          <div class= 'flex gap-8 items-center'>
            <img src="<%= user.photo %>" alt="<%= user.name %>" class='w-32 h-32 rounded-full'>
            <h2 class=' text-3xl'>
              <%= user.name %>
            </h2>
            <p>
              <%= user.posts_counter %>
              posts
            </p>
          </div>

        <%end %>
      </div>

  <% end %>
</div>

app/views/users/show.html.erb
<div class=' flex flex-col gap-8 mt-8'>
  <div class='flex gap-8 items-center'>
    <img src="<%= @user.photo %>" alt="<%= @user.name %>" class='w-32 h-32 rounded-full'>
    <div class="flex flex-col">
      <h1 class=" text-3xl"><%= @user.name %></h1>
      <p><%= @user.posts_counter%> posts</p>
    </div>
  </div>

  <div class=' flex flex-col shadow-md shadow-slate-400 p-4 rounded-md gap-4'>
    <h2 class='text-2xl'>Bio</h2>
    <p><%= @user.bio %></p>
  </div>

  <div class=' flex flex-col gap-8'>
    <%@recent_posts.each_with_index do |post, idx|%>
      <%= link_to user_post_path(user_id: @user.id, id: post.id) do %>
        <div class="flex flex-col gap-4 bg-slate-500 text-white p-4 rounded-lg">
          <p class=' text-xl'>Post <%= idx + 1 %></p>
          <h2 class=' text-3xl'><%= post.title %></h2>
          <p class=' pl-8'><%= post.text %></p>

          <div class='flex self-end gap-4 bg-white p-4 text-slate-800 rounded-md'>
            <p ><%=post.comments_counter %> comments</p>
            <p><%=post.likes_counter %> likes</p>
          </div>
        </div>
      <% end %>

    <% end %>
  </div>

  <div class=' self-center mb-8 shadow-md shadow-slate-400 p-4 rounded-md  '>
    <%= button_to "See all posts", user_posts_path(@user.id), method:'get' %>
  </div>
</div>